16:13:17  [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 13.727 s <<< FAILURE! - in com.personalcapital.profile.TargetPortfolioAccuracyCalculatorTest
16:13:17  [ERROR] com.personalcapital.profile.TargetPortfolioAccuracyCalculatorTest.testCalculateTargetPortfolioCompletionForCloseToRetirement  Time elapsed: 0.002 s  <<< ERROR!
16:13:17  java.lang.IllegalStateException: Failed to load ApplicationContext for [MergedContextConfiguration@496522b5 testClass = com.personalcapital.profile.TargetPortfolioAccuracyCalculatorTest, locations = ["classpath:pcapPlanningApplicationContext.xml"], classes = [], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [PropertySourceDescriptor[locations=[classpath:application-test-planning.properties], ignoreResourceNotFound=false, name=null, propertySourceFactory=null, encoding=null]], propertySourceProperties = [], contextCustomizers = [org.springframework.test.context.support.DynamicPropertiesContextCustomizer@0], contextLoader = org.springframework.test.context.support.DelegatingSmartContextLoader, parent = null]
16:13:17  Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'snapshotPersistenceReadOnlyUnitManager' defined in URL [file:/home/jenkins/agent/workspace/build_fp_pcap-fp-service_MR-5353/pcap-fp-repo/spring/pcap-snapshot-test-data.xml]: Failed to look up DataSource bean with name 'snapshotReadOnlyDataSource'
16:13:17  Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up DataSource bean with name 'snapshotReadOnlyDataSource'
16:13:17  Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'snapshotReadOnlyDataSource' defined in URL [file:/home/jenkins/agent/workspace/build_fp_pcap-fp-service_MR-5353/pcap-fp-repo/spring/pcap-snapshot-test-data.xml]: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Constructor threw exception
16:13:17  Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Constructor threw exception
16:13:17  Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:aws-wrapper:mysql://pcap-devtrunk-aurora-sp-schema-v1.cluster-ro-cofa2vnzxbaz.us-west-2.rds.amazonaws.com:3306/pcap_snapshot?socketTimeout=600000&connectTimeout=15000&elideSetAutoCommits=false&useLocalSessionState=false&characterEncoding=UTF-8
16:13:17  Caused by: java.sql.SQLException: Connector/J cannot handle a connection string 'jdbc:aws-wrapper:mysql://pcap-devtrunk-aurora-sp-schema-v1.cluster-ro-cofa2vnzxbaz.us-west-2.rds.amazonaws.com:3306/pcap_snapshot?socketTimeout=600000&connectTimeout=15000&elideSetAutoCommits=false&useLocalSessionState=false&characterEncoding=UTF-8'.
16:13:17  
16:13:17  [ERROR] com.personalcapital.profile.TargetPortfolioAccuracyCalculatorTest.testCalculateTargetPortfolioCompletionForNotCloseToRetirement  Time elapsed: 0 s  <<< ERROR!
16:13:17  java.lang.IllegalStateException: ApplicationContext failure threshold (1) exceeded: skipping repeated attempt to load context for [MergedContextConfiguration@496522b5 testClass = com.personalcapital.profile.TargetPortfolioAccuracyCalculatorTest, locations = ["classpath:pcapPlanningApplicationContext.xml"], classes = [], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [PropertySourceDescriptor[locations=[classpath:application-test-planning.properties], ignoreResourceNotFound=false, name=null, propertySourceFactory=null, encoding=null]], propertySourceProperties = [], contextCustomizers = [org.springframework.test.context.support.DynamicPropertiesContextCustomizer@0], contextLoader = org.springframework.test.context.support.DelegatingSmartContextLoader, parent = null]
